name: Build and compile for macOS

on:
  workflow_dispatch

jobs:
  build:
    name: Build for macOS
    runs-on: macos-latest
    strategy:
      matrix:
        dotnet: [ '6.0.x', '8.0.x' ]
    name: Dotnet ${{ matrix.dotnet }} sample


    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
          dotnet-version: ${{ matrix.dotnet }}
        
    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --output ./build

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish

    - name: Archive build output
      uses: actions/upload-artifact@v4 #once again, fuck you vibes based coding
      with:
        name: macos-build
        path: ./publish
