name: Build for macOS

on:
    workflow_dispatch

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0' # .NET 7 for the main project

    - name: Set up .NET Core SDK 6.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0' # .NET 6 for specific projects
    
    - name: Restore dependencies for .NET 7 projects
      run: dotnet restore --exclude GLFrameWorkEngine/GLFrameWorkEngine.csproj --exclude MapStudio.UI/MapStudio.UI.csproj --exclude Toolbox.Core/Toolbox.Core.csproj

    - name: Restore dependencies for .NET 6 projects
      run: dotnet restore --project GLFrameWorkEngine/GLFrameWorkEngine.csproj
      
    - name: Restore dependencies for .NET 6 projects
      run: dotnet restore --project MapStudio.UI/MapStudio.UI.csproj

    - name: Restore dependencies for .NET 6 projects
      run: dotnet restore --project Toolbox.Core/Toolbox.Core.csproj

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish --configuration Release -r osx-x64 --self-contained false

    - name: Create Artifact
      run: mkdir output && cp -r bin/Release/net7.0/osx-x64/publish/* output

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Track-Studio-macOS
        path: output
