name: Build and compile for macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build for macOS
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --output ./build

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish

    - name: Archive build output
      uses: actions/upload-artifact@v2
      with:
        name: macos-build
        path: ./publish
